'use client';
import {useEffect,useRef,useState,FormEvent} from 'react';
import {Terminal,Flag,Trophy,ArrowUpRight,ArrowRight,ChevronRight,Globe,Code2,KeyRound,Radio,Box,Flame,Clock,Check,Download,LogOut,X,LoaderCircle,RotateCcw,ShieldCheck,Copy} from 'lucide-react';
type Challenge={id:string;name:string;category:string;description:string;tier:string;points:number;delivery:'http'|'tcp'|'static';artifact:string|null;solve_count:number};
type Player={id:string;username:string;aura:number;solves:string[]};
type Instance={id:string;challenge_id:string;status:string;endpoint:string;expires_at:string};
type Board={players:{username:string;aura:number;solves:number}[];firstBloods:{username:string;name:string;solved_at:string}[]};
const categories=['All challenges','Web','Pwn','Reverse','Crypto','Forensics'];
const icons:Record<string,typeof Globe>={Web:Globe,Pwn:Terminal,Reverse:Code2,Crypto:KeyRound,Forensics:Radio};
async function api(path:string,options:RequestInit={}){
  const response=await fetch(`/api${path}`,{...options,headers:{'Content-Type':'application/json',...options.headers},credentials:'same-origin'});
  let data;try{data=await response.json();}catch{throw new Error('The arena is offline. Check the platform services.');}
  if(!response.ok)throw new Error(data.error || 'Request failed');return data;
}
function Countdown({expires}:{expires:string}){
  const [left,setLeft]=useState(Math.max(0,Math.ceil((new Date(expires).getTime()-Date.now())/1000)));
  useEffect(()=>{const t=setInterval(()=>setLeft(Math.max(0,Math.ceil((new Date(expires).getTime()-Date.now())/1000))),1000);return()=>clearInterval(t);},[expires]);
  return <span className={left<60?'danger':''}>{left===0?'Sent to the Void 💀':`Aura Depletion in ${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`}</span>;
}
export default function Arena(){
  const [catalog,setCatalog]=useState<Challenge[]>([]),[player,setPlayer]=useState<Player|null>(null),[board,setBoard]=useState<Board>({players:[],firstBloods:[]});
  const [category,setCategory]=useState('All challenges'),[tab,setTab]=useState('challenges'),[instance,setInstance]=useState<Instance|null>(null);
  const [selected,setSelected]=useState<Challenge|null>(null),[flag,setFlag]=useState(''),[busy,setBusy]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const [authMode,setAuthMode]=useState<'register'|'login'>('register'),[authOpen,setAuthOpen]=useState(false),[notice,setNotice]=useState<{text:string;good:boolean}|null>(null);
  const dialog=useRef<HTMLDialogElement>(null),authDialog=useRef<HTMLDialogElement>(null);
  const refresh=async()=>{
    try{const [c,b]=await Promise.all([api('/challenges'),api('/scoreboard')]);setCatalog(c.challenges);setBoard(b);setError('');}
    catch(e){setError((e as Error).message);}finally{setLoading(false);}
  };
  const refreshPlayer=async()=>{try{setPlayer(await api('/me'));setInstance((await api('/instances/current')).instance);}catch{setPlayer(null);setInstance(null);}};
  useEffect(()=>{void refresh();void refreshPlayer();const t=setInterval(()=>{void refresh();void refreshPlayer();},15000);return()=>clearInterval(t);},[]);
  useEffect(()=>{if(selected)dialog.current?.showModal();else dialog.current?.close();},[selected]);
  useEffect(()=>{if(authOpen)authDialog.current?.showModal();else authDialog.current?.close();},[authOpen]);
  useEffect(()=>{if(notice){const t=setTimeout(()=>setNotice(null),7000);return()=>clearTimeout(t);}},[notice]);
  const toast=(text:string,good=false)=>setNotice({text,good});
  const choose=(c:Challenge)=>{setFlag('');setSelected(c);};
  const signIn=()=>{setSelected(null);setAuthOpen(true);};
  const spawn=async()=>{
    if(!player)return signIn();if(!selected)return;setBusy('spawn');
    try{setInstance((await api(`/challenges/${selected.id}/spawn`,{method:'POST',body:'{}'})).instance);toast('Cooked & Live 🔥',true);}
    catch(e){toast((e as Error).message);}finally{setBusy('');}
  };
  const stop=async()=>{setBusy('stop');try{await api('/instances/current',{method:'DELETE'});setInstance(null);toast('Sent to the Void 💀',true);}catch(e){toast((e as Error).message);}finally{setBusy('');}};
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!player)return signIn();if(!selected)return;setBusy('flag');try{const r=await api(`/challenges/${selected.id}/submit`,{method:'POST',body:JSON.stringify({flag})});toast(`${r.message}${r.firstBlood?' GIGACHAD BLOOD 🩸':''}`,r.correct);if(r.correct){setFlag('');await refreshPlayer();await refresh();}}catch(e){toast((e as Error).message);}finally{setBusy('');}};
  const authenticate=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);setBusy('auth');try{await api(`/auth/${authMode}`,{method:'POST',body:JSON.stringify({username:form.get('username'),password:form.get('password')})});await refreshPlayer();setAuthOpen(false);toast('You’re in. Make your move.',true);}catch(e){toast((e as Error).message);}finally{setBusy('');}};
  const current=instance && new Date(instance.expires_at)>new Date()?instance:null;
  const filtered=catalog.filter(c=>category==='All challenges'||c.category===category);
  const solved=selected && player?.solves.includes(selected.id);
  return <div className="shell">
    <aside className="sidebar">
      <a href="/" className="brand" aria-label="SigmaCTF home"><span className="brand-mark">Σ</span><span>SIGMA<span className="green">CTF</span><small>CAPTURE THE FLAG</small></span></a>
      <div className="season"><span className="live-dot"/> THE ARENA IS YOURS <span>01</span></div>
      <nav aria-label="Main navigation"><p className="eyebrow">PLAYGROUND</p><button className={tab==='challenges'?'nav-item active':'nav-item'} onClick={()=>setTab('challenges')}><Flag size={18}/> Challenges <span className="nav-count">{catalog.length.toString().padStart(2,'0')}</span></button><button className={tab==='scoreboard'?'nav-item active':'nav-item'} onClick={()=>setTab('scoreboard')}><Trophy size={18}/> Sigma Scoreboard <ChevronRight size={15}/></button></nav>
      <div className="sidebar-note"><Terminal size={20}/><p>Less talk.<br/><strong>More flags.</strong></p><div className="mini-code">$ skill --issue<br/><span>command not found_</span></div></div>
      <div className="sidebar-bottom"><div className="status-line"><span className={error?'live-dot red':'live-dot'}/>{error?'API OFFLINE':'LOCAL-FIRST ARENA'}</div><span className="muted">SIGMACTF / v1.0</span></div>
    </aside>
    <div className="workspace">
      <header className="topbar"><div className="breadcrumb">arena <span>/</span> <strong>{tab}</strong><span className="cursor">_</span></div><div className="account">{player?<><span className="aura-text">{player.aura} AURA</span><span className="avatar">{player.username.slice(0,2).toUpperCase()}</span><span className="username">{player.username}</span><button className="icon-button" aria-label="Sign out" onClick={async()=>{try{await api('/auth/logout',{method:'POST',body:'{}'});setPlayer(null);setInstance(null);}catch(e){toast((e as Error).message);}}}><LogOut size={16}/></button></>:<><span className="guest-label">GUEST SESSION</span><button className="small-button" onClick={signIn}>Enter the arena <ArrowUpRight size={15}/></button></>}</div></header>
      <main>
        <div className="page-heading"><div><div className="eyebrow green">// {tab==='challenges'?'BREAK THINGS. BUILD AURA.':'THE RECEIPTS ARE PUBLIC.'}</div><h1>{tab==='challenges'?'Choose your battleground.':'Sigma Scoreboard.'}</h1><p>{tab==='challenges'?'Five disciplines. Zero hand-holding. Your next flag is waiting.':'Earn your place. Every flag counts.'}</p></div><span className="outline-badge"><span className="live-dot"/> OPEN PRACTICE</span></div>
        <div className="stats-grid"><div className="stat"><div><span>YOUR AURA</span><Flame size={17}/></div><strong className="purple">{player?.aura || 0}<small>AURA</small></strong><p>{player?'Your reputation, earned.':'Every sigma starts at zero.'}</p></div><div className="stat"><div><span>FLAGS CAPTURED</span><Flag size={17}/></div><strong>{String(player?.solves.length || 0).padStart(2,'0')}<small>/ {String(catalog.length).padStart(2,'0')}</small></strong><div className="progress-track"><span style={{width:`${catalog.length?(player?.solves.length||0)/catalog.length*100:0}%`}}/></div></div><div className="stat"><div><span>YOUR SANDBOX</span><Box size={17}/></div><strong className={current?'green':'muted'}>{current?'LIVE':'STANDBY'}<span className={current?'live-dot':'standby-dot'}/></strong><p>{current?<Countdown expires={current.expires_at}/>: 'Launch a challenge. Let it cook.'}</p></div></div>
        {tab==='challenges'?<>
          <div className="catalog-toolbar"><div className="category-tabs" aria-label="Filter challenges">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} aria-pressed={category===c} className={category===c?'selected':''}>{c}{c==='All challenges'&&<span>{catalog.length}</span>}</button>)}</div><span className="results-count">{filtered.length} challenges</span></div>
          {error?<div className="empty-state"><Terminal/><h2>The arena is offline.</h2><p>{error}</p><button className="small-button" onClick={()=>{setLoading(true);void refresh();}}>Retry connection <RotateCcw size={16}/></button></div>:loading?<div className="empty-state"><LoaderCircle className="spin"/><p>Loading the arena...</p></div>:<div className="challenge-grid">{filtered.map((c,index)=>{const Icon=icons[c.category];const done=player?.solves.includes(c.id);const active=current?.challenge_id===c.id;return <button className={`challenge-card ${done?'solved-card':''}`} key={c.id} onClick={()=>choose(c)} aria-label={`Open ${c.name}`}><div className="card-top"><span className={`category-icon ${c.category.toLowerCase()}`}><Icon size={22}/></span><span className="tier">{c.tier==='Sigma Tier'&&<span className="gold">◆ </span>}{c.tier}</span><span className="card-number">/{String(index+1).padStart(2,'0')}</span></div><div className="category-label">{c.category.toUpperCase()} <span>•</span> {c.delivery==='static'?'FILE DOWNLOAD':c.delivery==='http'?'WEB INSTANCE':'TCP INSTANCE'}</div><h2>{c.name}</h2><p className="description">{c.description}</p><div className="card-footer"><strong className="purple">+{c.points} <span>Aura</span></strong><span>{done?<><Check size={14}/> Captured</>:active?<><span className="live-dot"/> Live</>:<>{c.solve_count} solves <ArrowUpRight size={17}/></>}</span></div></button>;})}<div className="manifesto-card"><div className="ascii-sigma">[ Σ ]</div><h2>Proof of skill.<br/>No proof of hype.</h2><p>Find the weakness.<br/>Capture the flag.<br/>Let the scoreboard talk.</p><span>STAY CURIOUS. STAY DANGEROUS.</span></div></div>}
        </>:<div className="scoreboard-panel"><div className="section-title"><Trophy size={18}/><h2>The Aura leaderboard</h2><span>LIVE / 15s</span></div>{board.players.length?<div className="table-scroll"><table><thead><tr><th>RANK</th><th>PLAYER</th><th>FLAGS</th><th>AURA</th></tr></thead><tbody>{board.players.map((p,i)=><tr key={p.username} className={p.username===player?.username?'your-row':''}><td className={i===0?'gold':''}>{String(i+1).padStart(2,'0')}</td><td>{p.username}{i===0&&<Trophy className="gold" size={16}/>}</td><td>{p.solves}</td><td className="purple">{p.aura}</td></tr>)}</tbody></table></div>:<div className="empty-state"><Trophy className="gold"/><h2>The throne is empty.</h2><p>Capture a flag to claim the first spot.</p><button className="small-button" onClick={()=>setTab('challenges')}>Find a challenge <ArrowRight size={16}/></button></div>}</div>}
        <div className="activity-bar"><span className="gold"><Flame size={16}/> FIRST BLOOD</span>{board.firstBloods.length?<p><strong>{board.firstBloods[0].username}</strong> claimed {board.firstBloods[0].name} <span className="gold">// GIGACHAD BLOOD 🩸</span></p>:<p>No first blood yet. <strong>Make the first move.</strong></p>}<button onClick={()=>setTab('scoreboard')} aria-label="View scoreboard"><ArrowUpRight size={18}/></button></div>
        <footer><span>BUILT FOR THE CURIOUS. OWN THE CHALLENGE.</span><span><ShieldCheck size={14}/> ISOLATED SESSIONS <span className="footer-divider">/</span> 15 MIN TTL</span></footer>
      </main>
    </div>
    <dialog ref={dialog} onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===dialog.current)setSelected(null);}} aria-labelledby="challenge-title">
      {selected&&<div className="modal-content"><div className="modal-top"><span className="eyebrow green">{selected.category.toUpperCase()} / {selected.tier.toUpperCase()}</span><button className="icon-button" onClick={()=>setSelected(null)} aria-label="Close challenge"><X size={20}/></button></div><h2 id="challenge-title">{selected.name}</h2><div className="modal-meta"><span className="purple">+{selected.points} Aura</span><span>{selected.solve_count} solves</span></div><p className="modal-description">{selected.description}</p>
      {selected.artifact&&<a className="download-button" href={`/api/challenges/${selected.id}/artifact`}><Download size={17}/> Download {selected.artifact}<ArrowUpRight size={16}/></a>}
      {selected.delivery!=='static'&&<div className="instance-box">{current?.challenge_id===selected.id?<><div className="instance-title"><span className="green"><span className="live-dot"/> Cooked &amp; Live 🔥</span><button disabled={!!busy} className="text-button" onClick={stop}>Terminate</button></div><div className="endpoint">{selected.delivery==='http'?<a href={current.endpoint} target="_blank" rel="noreferrer">Open challenge <ArrowUpRight size={16}/></a>:<code>{current.endpoint}</code>}<button aria-label="Copy connection" className="icon-button" onClick={async()=>{try{await navigator.clipboard.writeText(current.endpoint);toast('Connection copied.',true);}catch{toast('Copy unavailable. Select the connection text.');}}}><Copy size={16}/></button></div><div className="instance-clock"><Clock size={14}/><Countdown expires={current.expires_at}/></div></>:<><div className="sandbox-spec"><Box size={18}/><span>Private sandbox</span><span>15 minutes</span></div>{current&&<p className="replacement-note">Launching this challenge will terminate your current instance.</p>}<button className="primary-button" disabled={!!busy} onClick={spawn}>{busy==='spawn'?<><LoaderCircle size={18} className="spin"/> Cooking container in Ohio...</>:<><Flame size={18}/> Let Him Cook <ArrowUpRight size={18}/></>}</button></>}</div>}
      <form onSubmit={submit} className="flag-form"><label htmlFor="flag-input">{solved?'FLAG CAPTURED':'CAPTURE THE FLAG'}</label><div className="flag-input-row"><Terminal size={18}/><input id="flag-input" placeholder="sigma{your_flag_here}" value={flag} onChange={e=>setFlag(e.target.value)} required maxLength={256} disabled={!!solved} autoComplete="off"/><button type="submit" disabled={!!busy||!!solved}>{solved?<Check size={18}/>:busy==='flag'?<LoaderCircle className="spin" size={18}/>:<ArrowRight size={18}/>}<span className="sr-only">Submit flag</span></button></div><p>{player?'5 checks per minute. Make them count.':'Sign in to launch instances and submit flags.'}</p></form></div>}
    </dialog>
    <dialog ref={authDialog} onCancel={()=>setAuthOpen(false)} aria-labelledby="auth-title"><div className="modal-content"><div className="modal-top"><span className="eyebrow green">// IDENTIFY YOURSELF</span><button className="icon-button" onClick={()=>setAuthOpen(false)} aria-label="Close sign in"><X size={20}/></button></div><h2 id="auth-title">{authMode==='register'?'Enter the arena.':'Welcome back.'}</h2><p className="modal-description">Your handle. Your flags. Your Aura.</p><form className="auth-form" onSubmit={authenticate}><label htmlFor="username">HANDLE</label><input id="username" name="username" required pattern="[A-Za-z0-9_]{3,24}" minLength={3} maxLength={24} autoComplete="username" placeholder="your_handle"/><small>3–24 letters, numbers, or underscores.</small><label htmlFor="password">PASSWORD</label><input id="password" type="password" name="password" required minLength={12} maxLength={128} autoComplete={authMode==='register'?'new-password':'current-password'} placeholder="At least 12 characters"/><button className="primary-button" disabled={!!busy}>{busy==='auth'?<LoaderCircle className="spin" size={18}/>:<>{authMode==='register'?'Create account':'Sign in'}<ArrowRight size={18}/></>}</button></form><button className="auth-switch" onClick={()=>setAuthMode(authMode==='register'?'login':'register')}>{authMode==='register'?'Already in the arena? Sign in':'New here? Create an account'}</button></div></dialog>
    {notice&&<div className={`toast ${notice.good?'good':'bad'}`} role="status"><span>{notice.good?<Check size={18}/>:<Terminal size={18}/>}</span><p>{notice.text}</p><button aria-label="Dismiss notification" onClick={()=>setNotice(null)}><X size={16}/></button></div>}
  </div>;
}

